Replace scons with cmake
precice/6dof-rigid-body-solver pull request #4
Opened 2020-03-29 19:02 UTC by DavidSCN

Replaces scons with cmake.

Only part I am not sure: The `Tests.hpp` are directly included in the main file. So, we don't set up a ctest target, but compile directly with make, right? We can then chose at runtime, if we want to run a test by passing `tests` as argument instead of `precice-config.xml`.

Closes #1

2020-03-30 13:31 UTC, uekerman commented
The tests use (deprecated) data structures from preCICE. I would suggest to not build them at all at the moment. Instead, you could open an issue that tests need to be ported to some independent framework.

2020-04-02 10:55 UTC, fsimonis requested changes

2020-04-02 10:55 UTC, fsimonis commented on CMakeLists.txt
> +set_target_properties(${TARGET} PROPERTIES CXX_STANDARD 11)
Some lessons learned from the preCICE port to CMake:

```suggestion
set_target_properties(${TARGET} PROPERTIES
    CXX_STANDARD 11
    CXX_STANDARD_REQUIRED TRUE
    CXX_EXTENSIONS FALSE
    )
```

2020-04-03 13:50 UTC, fsimonis approved these changes

2020-04-03 18:22 UTC, davidscn commented
I will merge it first of all, although it will not compile for other reasons.

2020-04-03 18:22 UTC, merged